=== bspies/ainur/packages/build/src/schema/config.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#", 
    "id": "https://github.com/bspies/ainur/config.schema.json",
    "type": "object",
    "properties": {
        "root": {
            "type": "string"
        },
        "features": {
            "type": "array",
            "items": {"type": "string"}
        },
        "output": {
            "type": "object",
            "properties": {
                "bundles": {
                    "type": "object"
                },
                "html": {
                    "type": "array"
                }
            }
        },
        "source": {
            "type": "object",
            "properties": {
                "excludes" : {
                    "oneOf":[
                        { "type": "string" },
                        { "type": "array", "items": {"type": "string"} }
                    ]
                },
                "level": {
                    "type": "string"
                },
                "lint": {
                    "type": "boolean"
                },
                "maps": {
                    "type": "string"
                }
            }
        },
        "targets": {
            "type": "object",
            "oneOf":[
                {
                    "properties": {
                        "browsers": {
                            "type": "array"
                        }
                    }
                },
                {
                    "properties": {
                        "node": {
                            "type": "string"
                        }
                    }
                }
            ]
        }
    }
}

=== bspies/ainur/packages/build/config.json
{
    "source": {
        "level": "es6",
        "excludes": "__tests__"
    },
    "output": {
        "dir": "./dist",
        "bundles": {
            "main": ["./src"]
        },
        "html": []
    },
    "targets": {
        "browsers": ["ie11", "chrome", "firefox"],
        "node": "current"
    }, 
    "features": ["react", "angular", "bootstrap"]
}
